---
vector_config:
  sources:
  my_source_id:
    type: file
    ignore_older_secs: 600
    include:
      - /var/log/**/*.log
    read_from: beginning
  sinks:
  to_clickhouse:
    type: clickhouse
    inputs:
      - our_log
    database: custom
    endpoint: http://51.250.94.239:8123
    table: my_table
    compression: gzip
    healthcheck: false
    skip_unknown_fields: true